#include "LGLKeyToStringMap.h"
#include <GLFW/glfw3.h>

NaiveBidirMap<int, std::string> LGLKeyToStringMap::keyToStringMap =
{
    { GLFW_KEY_SPACE, "Space" },
    { GLFW_KEY_APOSTROPHE, "'" },
    { GLFW_KEY_COMMA, "," },
    { GLFW_KEY_MINUS, "-" },
    { GLFW_KEY_PERIOD, "." },
    { GLFW_KEY_SLASH, "/" },
    { GLFW_KEY_0, "0" }, { GLFW_KEY_1, "1" }, { GLFW_KEY_2, "2" },
    { GLFW_KEY_3, "3" }, { GLFW_KEY_4, "4" }, { GLFW_KEY_5, "5" },
    { GLFW_KEY_6, "6" }, { GLFW_KEY_7, "7" }, { GLFW_KEY_8, "8" },
    { GLFW_KEY_9, "9" },
    { GLFW_KEY_SEMICOLON, ";" },
    { GLFW_KEY_EQUAL, "=" },
    { GLFW_KEY_A, "A" }, { GLFW_KEY_B, "B" }, { GLFW_KEY_C, "C" },
    { GLFW_KEY_D, "D" }, { GLFW_KEY_E, "E" }, { GLFW_KEY_F, "F" },
    { GLFW_KEY_G, "G" }, { GLFW_KEY_H, "H" }, { GLFW_KEY_I, "I" },
    { GLFW_KEY_J, "J" }, { GLFW_KEY_K, "K" }, { GLFW_KEY_L, "L" },
    { GLFW_KEY_M, "M" }, { GLFW_KEY_N, "N" }, { GLFW_KEY_O, "O" },
    { GLFW_KEY_P, "P" }, { GLFW_KEY_Q, "Q" }, { GLFW_KEY_R, "R" },
    { GLFW_KEY_S, "S" }, { GLFW_KEY_T, "T" }, { GLFW_KEY_U, "U" },
    { GLFW_KEY_V, "V" }, { GLFW_KEY_W, "W" }, { GLFW_KEY_X, "X" },
    { GLFW_KEY_Y, "Y" }, { GLFW_KEY_Z, "Z" },
    { GLFW_KEY_LEFT_BRACKET, "[" },
    { GLFW_KEY_BACKSLASH, "\\" },
    { GLFW_KEY_RIGHT_BRACKET, "]" },
    { GLFW_KEY_GRAVE_ACCENT, "`" },
    { GLFW_KEY_ESCAPE, "Escape" },
    { GLFW_KEY_ENTER, "Enter" },
    { GLFW_KEY_TAB, "Tab" },
    { GLFW_KEY_BACKSPACE, "Backspace" },
    { GLFW_KEY_INSERT, "Insert" },
    { GLFW_KEY_DELETE, "Delete" },
    { GLFW_KEY_RIGHT, "RightArrow" },
    { GLFW_KEY_LEFT, "LeftArrow" },
    { GLFW_KEY_DOWN, "DownArrow" },
    { GLFW_KEY_UP, "UpArrow" },
    { GLFW_KEY_PAGE_UP, "PageUp" },
    { GLFW_KEY_PAGE_DOWN, "PageDown" },
    { GLFW_KEY_HOME, "Home" },
    { GLFW_KEY_END, "End" },
    { GLFW_KEY_CAPS_LOCK, "CapsLock" },
    { GLFW_KEY_SCROLL_LOCK, "ScrollLock" },
    { GLFW_KEY_NUM_LOCK, "NumLock" },
    { GLFW_KEY_PRINT_SCREEN, "PrintScreen" },
    { GLFW_KEY_PAUSE, "Pause" },
    { GLFW_KEY_F1, "F1" }, { GLFW_KEY_F2, "F2" }, { GLFW_KEY_F3, "F3" },
    { GLFW_KEY_F4, "F4" }, { GLFW_KEY_F5, "F5" }, { GLFW_KEY_F6, "F6" },
    { GLFW_KEY_F7, "F7" }, { GLFW_KEY_F8, "F8" }, { GLFW_KEY_F9, "F9" },
    { GLFW_KEY_F10, "F10" }, { GLFW_KEY_F11, "F11" }, { GLFW_KEY_F12, "F12" },
    { GLFW_KEY_LEFT_SHIFT, "LeftShift" },
    { GLFW_KEY_LEFT_CONTROL, "LeftCtrl" },
    { GLFW_KEY_LEFT_ALT, "LeftAlt" },
    { GLFW_KEY_LEFT_SUPER, "LeftSuper" },
    { GLFW_KEY_RIGHT_SHIFT, "RightShift" },
    { GLFW_KEY_RIGHT_CONTROL, "RightCtrl" },
    { GLFW_KEY_RIGHT_ALT, "RightAlt" },
    { GLFW_KEY_RIGHT_SUPER, "RightSuper" },
    { GLFW_KEY_MENU, "Menu" }
};
