name: MSBuild

on:
  push:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: write
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Build
      run: msbuild ProjectEverett.sln /p:Configuration=${{env.BUILD_CONFIGURATION}}

    - name: Zip Release Folder
      run: Compress-Archive -Path ".\\x64\\Release\\*" -DestinationPath "EverettEngine.zip"

    - name: Delete previous nightly build
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ github.token }}
        tag: nightly
        assets: 'EverettEngine.zip'
        fail-if-no-release: false
        fail-if-no-assets: false

    - name: Upload new nightly build
      uses: softprops/action-gh-release@v1
      with:
        tag_name: nightly
        name: Nightly Build
        files: EverettEngine.zip
        draft: false
        prerelease: true
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
